### ISSUE TITLE
Syntax error when authentication fails

### ISSUE THREAD

**Issue by pkoevesdi** [kbsali/php-redmine-api#335]
When I call 
```
    try {
    $client = new \Redmine\Client\NativeCurlClient('https://redmine.example.com', $_GET["key"]);
    $client->setCurlOption(CURLOPT_SSL_VERIFYPEER, true);
    $issues = $client->getApi('issue')->list([
        'limit' => 10000,
        'query_id' => $_GET["query_id"]
    ]);
    } catch (\Redmine\Exception $e) {
        echo "Redmine error: <pre>$e</pre>";
        exit();
    } catch (\Throwable $e) {
        echo "Other error: <pre>$e</pre>";
        exit();
    }
```
with a wrong "key" provided (401 response), I get the following error:
```
JsonException: Syntax error in /var/www/html/utils/tasklist/vendor/kbsali/redmine-api/src/Redmine/Serializer/JsonSerializer.php:69
Stack trace:
#0 /var/www/html/utils/tasklist/vendor/kbsali/redmine-api/src/Redmine/Serializer/JsonSerializer.php(69): json_decode()
#1 /var/www/html/utils/tasklist/vendor/kbsali/redmine-api/src/Redmine/Serializer/JsonSerializer.php(20): Redmine\Serializer\JsonSerializer->decode()
#2 /var/www/html/utils/tasklist/vendor/kbsali/redmine-api/src/Redmine/Api/AbstractApi.php(317): Redmine\Serializer\JsonSerializer::createFromString()
#3 /var/www/html/utils/tasklist/vendor/kbsali/redmine-api/src/Redmine/Api/AbstractApi.php(234): Redmine\Api\AbstractApi->getLastResponseBodyAsArray()
#4 /var/www/html/utils/tasklist/vendor/kbsali/redmine-api/src/Redmine/Api/Issue.php(45): Redmine\Api\AbstractApi->retrieveData()
#5 /var/www/html/utils/tasklist/index.php(29): Redmine\Api\Issue->list()
#6 {main}

Next Redmine\Exception\SerializerException: Catched error "Syntax error" while decoding JSON:  in /var/www/html/utils/tasklist/vendor/kbsali/redmine-api/src/Redmine/Serializer/JsonSerializer.php:76
Stack trace:
#0 /var/www/html/utils/tasklist/vendor/kbsali/redmine-api/src/Redmine/Serializer/JsonSerializer.php(20): Redmine\Serializer\JsonSerializer->decode()
#1 /var/www/html/utils/tasklist/vendor/kbsali/redmine-api/src/Redmine/Api/AbstractApi.php(317): Redmine\Serializer\JsonSerializer::createFromString()
#2 /var/www/html/utils/tasklist/vendor/kbsali/redmine-api/src/Redmine/Api/AbstractApi.php(234): Redmine\Api\AbstractApi->getLastResponseBodyAsArray()
#3 /var/www/html/utils/tasklist/vendor/kbsali/redmine-api/src/Redmine/Api/Issue.php(45): Redmine\Api\AbstractApi->retrieveData()
#4 /var/www/html/utils/tasklist/index.php(29): Redmine\Api\Issue->list()
#5 {main}
```

Happens in `commit/5277a937ed62eff7670d98662ee993551c7cb8a7`.
With the right API key, everything works fine.

**Comment by Art4** [comment]
Thank you very much for reporting this issue. I will investigate it next week.

If you already have a solution I would be glad about a PR.

**Comment by pkoevesdi** [comment]
Sorry, I didn't really look at it, at first glance I wasn't able to see a syntax error there.

**Comment by Art4** [comment]
I was able to reproduce this error. The cause is not an invalid key, but an invalid `query_id` parameter.

Requesting `https://redmine.example.com/issues.json?limit=2&query_id=null` lets Redmine response with a 404 error and an empty body. Using this empty body in `json_decode()` then leads to the observed error. So a bugfix would be a better error handling of the response body.

**Comment by pkoevesdi** [comment]
Nice, thanks!
